# Override file for local development
services:
  frontend:
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8777
    ports:
      - "3001:3001"

  backend:
    environment:
      - LMSTUDIO_URL=http://host.docker.internal:1234/v1
      - SEARXNG_BASE_URL=http://searxng:8080
      - AGENT_MODE=react
