services:
  redis:
    container_name: agentic-seek-redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - agentic-seek-net

  searxng:
    container_name: agentic-seek-searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../searxng:/etc/searxng:rw,z
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY:-changeme}
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - redis
    networks:
      - agentic-seek-net

  backend:
    container_name: agentic-seek-backend
    build:
      context: ..
      dockerfile: ./apps/backend/Dockerfile
    restart: unless-stopped
    ports:
      - "7777:7777"
    environment:
      - NODE_ENV=production
      - PORT=7777
      - HOST=0.0.0.0
      - LLM_STUDIO_BASE_URL=http://host.docker.internal:1234/v1
      - SEARXNG_BASE_URL=http://searxng:8080
    depends_on:
      - searxng
    networks:
      - agentic-seek-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    container_name: agentic-seek-frontend
    build:
      context: ..
      dockerfile: ./apps/frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://backend:7777
    depends_on:
      - backend
    networks:
      - agentic-seek-net

volumes:
  redis-data:

networks:
  agentic-seek-net:
    driver: bridge
