general:
  debug: false
  instance_name: "AgenticSeek SearxNG"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true

brand:
  new_issue_url: https://github.com/searxng/searxng/issues/new
  docs_url: https://docs.searxng.org/
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
  issue_url: https://github.com/searxng/searxng/issues

search:
  safe_search: 0
  autocomplete: ""
  autocomplete_min: 4
  default_lang: "auto"
  theme: simple

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: changeme
  base_url: false
  image_proxy: false
  http_protocol_version: "1.0"

ui:
  static_path: ""
  static_use_hash: false
  templates_path: ""
  default_theme: simple
  default_locale: ""

engines:
  - name: duckduckgo
    engine: duckduckgo
    disabled: false

  - name: google
    engine: google
    disabled: false

  - name: wikipedia
    engine: wikipedia
    disabled: false

  - name: bing
    engine: bing
    disabled: false

